export const MenuItems = [
  {
    title: "Mercury",
    url: "#",
    cName: "nav__links ",
    cNameDot: "nav__links-dot-mercury",
    path: "/Mercury",
  },
  {
    title: "Venus",
    url: "#",
    cName: "nav__links",
    cNameDot: "nav__links-dot-venus",
    path: "/Venus",
  },
  {
    title: "Earth",
    url: "#",
    cName: "nav__links",
    cNameDot: "nav__links-dot-earth",
    path: "/Earth",
  },
  {
    title: "Mars",
    url: "#",
    cName: "nav__links",
    cNameDot: "nav__links-dot-mars",
    path: "/Mars",
  },
  {
    title: "Jupiter",
    url: "#",
    cName: "nav__links",
    cNameDot: "nav__links-dot-jupiter",
    path: "/Jupiter",
  },
  {
    title: "Saturn",
    url: "#",
    cName: "nav__links",
    cNameDot: "nav__links-dot-saturn",
    path: "/Saturn",
  },
  {
    title: "Uranus",
    url: "#",
    cName: "nav__links",
    cNameDot: "nav__links-dot-uranus",
    path: "/Uranus",
  },
  {
    title: "Neptune",
    url: "#",
    cName: "nav__links",
    cNameDot: "nav__links-dot-neptune",
    path: "/Neptune",
  },
];
